version = 1

[[annotations]]
path = [
    ".devcontainer/**",
    ".github/**",
    ".gitignore",
    ".pre-commit-config.yaml",
    ".env",
    "CHANGELOG.md",
    "Dockerfile",
    "README.md",
    "cliff.toml",
    "docs/**",
    "pyproject.toml",
    "requirements.txt",
    "requirements-dev.txt",
    "tox.ini",
    "uv.lock",
    "benchmarks/results/.gitignore",
    "benchmarks/README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 the Glacier project contributors"
SPDX-License-Identifier = "BSD-2-Clause"
