[tox]
requires =
    tox>=4
env_list =
    py{312,313}
    formatter
    type
    coverage
skip_missing_interpreters = true

[testenv]
description = run the tests with pytest
skip_install = true
allowlist_externals =
    uv
commands_pre =
    uv sync --group test --python {envpython}
commands =
    uv run --python {envpython} pytest {posargs:tests}

[testenv:type]
description = run type checks
skip_install = true
allowlist_externals = uv
commands_pre =
    uv sync --group dev
commands =
    uv run mypy {posargs:frost_planner tests}

[testenv:formatter]
description = run linter
skip_install = true
allowlist_externals = uv
commands_pre =
    uv sync --group dev
commands =
    uv run ruff check --fix {posargs:frost_planner tests}
    uv run ruff format {posargs:frost_planner tests}

[testenv:coverage]
description = run coverage report
skip_install = true
allowlist_externals = uv
commands_pre =
    uv sync --group test
commands = uv run pytest --cov=frost_planner --cov-report=term-missing {posargs:tests}
